# Generated by Django 4.2.1 on 2023-06-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[(1, 'pending'), (2, 'Accepted'), (3, 'Rejected')], default=1, max_length=100),
        ),
    ]
