# Generated by Django 4.2.1 on 2023-06-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1, max_length=100),
        ),
    ]
